version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.6.0
    steps:
      - checkout
      - restore_cache:
          keys: [build]
      - run:
          name: Build
          command: |
            npm install
            npm run build
      - save_cache:
          paths: [node_modules]
          key: build

  scan:
    docker:
      - image: cimg/node:20.6.0
    steps:
      - checkout
      - restore_cache:
          keys: [build]
      - run:
          name: Scan 
          command: |
            npm install
            npm audit fix --audit-level=critical

  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install -y python3-pip
            sudo pip3 install awscli --upgrade
      - run:
          name: Deploying to AWS S3
          command: |
            aws s3 sync . s3://todoapplistccbc

workflows:
  version: 2
  build_and_scan_and_deploy:
    jobs:
      - build
      - scan:
          requires:
            - build
      - deploy:
          requires:
            - scan
